
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothScannerBinding$Listener ///

public protocol SwiftBluetoothScannerBinding_Listener: SwiftActivityBinding_Listener {

}


open class SwiftBluetoothScannerBinding_ListenerForward: SwiftActivityBinding_ListenerForward, SwiftBluetoothScannerBinding_Listener {

    private static var SwiftBluetoothScannerBinding_ListenerJNIClass: jclass?

}

private typealias SwiftBluetoothScannerBinding_Listener_viewDidLoad_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> ()

private func SwiftBluetoothScannerBinding_Listener_viewDidLoad_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> () {
    SwiftBluetoothScannerBinding_ListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).viewDidLoad( )
}

fileprivate class SwiftBluetoothScannerBinding_ListenerLocal_: JNILocalProxy<SwiftBluetoothScannerBinding_Listener, Any> {

    fileprivate static let _proxyClass: jclass = {
        var natives = [JNINativeMethod]()

        let SwiftBluetoothScannerBinding_Listener_viewDidLoad_0_thunk: SwiftBluetoothScannerBinding_Listener_viewDidLoad_0_type = SwiftBluetoothScannerBinding_Listener_viewDidLoad_0
        
        natives.append( JNINativeMethod( name: strdup("__viewDidLoad"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( SwiftBluetoothScannerBinding_Listener_viewDidLoad_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

        natives.append( JNINativeMethod( name: strdup("__finalize"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( JNIReleasableProxy__finalize_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let clazz = JNI.FindClass( proxyClassName() )
        natives.withUnsafeBufferPointer {
            nativesPtr in
            if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr.baseAddress, jint(nativesPtr.count) ) != jint(JNI_OK) {
                JNI.report( "Unable to register java natives" )
            }
        }

        defer { JNI.DeleteLocalRef( clazz ) }
        return JNI.api.NewGlobalRef( JNI.env, clazz )!
    }()

    override open class func proxyClassName() -> String { return "org/swiftjava/com_johnholdsworth/SwiftBluetoothScannerBinding_ListenerProxy" }
    override open class func proxyClass() -> jclass? { return _proxyClass }

}

extension SwiftBluetoothScannerBinding_Listener {

    public func localJavaObject( _ locals: UnsafeMutablePointer<[jobject]> ) -> jobject? {
        return SwiftBluetoothScannerBinding_ListenerLocal_( owned: self, proto: self ).localJavaObject( locals )
    }

}

open class SwiftBluetoothScannerBinding_ListenerBase: SwiftBluetoothScannerBinding_Listener {

    public init() {}

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftActivityBinding$Listener.viewDidLoad()

    open func viewDidLoad() /**/ {
    }


}
