
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothScannerBinding ///

public protocol SwiftBluetoothScannerBinding: SwiftActivityBinding {

}


open class SwiftBluetoothScannerBindingForward: SwiftActivityBindingForward, SwiftBluetoothScannerBinding {

    private static var SwiftBluetoothScannerBindingJNIClass: jclass?

}

