
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.kgr.swiftbindings.MainActivityBindings ///

public protocol MainActivityBindings: JavaProtocol {

}


open class MainActivityBindingsForward: JNIObjectForward, MainActivityBindings {

    private static var MainActivityBindingsJNIClass: jclass?

}

