
/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.kgr.swiftbindings.MainActivityBindings$Listener ///

package org.swiftjava.com_kgr;

@SuppressWarnings("JniMissingFunction")
public class MainActivityBindings_ListenerProxy implements com.kgr.swiftbindings.MainActivityBindings.Listener {

    // address of proxy object
    long __swiftObject;

    MainActivityBindings_ListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    /// public abstract void com.kgr.swiftbindings.MainActivityBindings$Listener.hello()

    public native void __hello( long __swiftObject );

    public void hello() {
        __hello( __swiftObject  );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
