
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.DevicesActivityBinding$Listener ///

public protocol DevicesActivityBinding_Listener: JavaProtocol {

    /// public abstract void com.johnholdsworth.swiftbindings.DevicesActivityBinding$Listener.startDiscovery()

    func startDiscovery()

    /// public abstract void com.johnholdsworth.swiftbindings.DevicesActivityBinding$Listener.validateBluetooth()

    func validateBluetooth()

}


open class DevicesActivityBinding_ListenerForward: JNIObjectForward, DevicesActivityBinding_Listener {

    private static var DevicesActivityBinding_ListenerJNIClass: jclass?

    /// public abstract void com.johnholdsworth.swiftbindings.DevicesActivityBinding$Listener.startDiscovery()

    private static var startDiscovery_MethodID_3: jmethodID?

    open func startDiscovery() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "startDiscovery", methodSig: "()V", methodCache: &DevicesActivityBinding_ListenerForward.startDiscovery_MethodID_3, args: &__args, locals: &__locals )
    }


    /// public abstract void com.johnholdsworth.swiftbindings.DevicesActivityBinding$Listener.validateBluetooth()

    private static var validateBluetooth_MethodID_4: jmethodID?

    open func validateBluetooth() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "validateBluetooth", methodSig: "()V", methodCache: &DevicesActivityBinding_ListenerForward.validateBluetooth_MethodID_4, args: &__args, locals: &__locals )
    }


}

private typealias DevicesActivityBinding_Listener_startDiscovery_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> ()

private func DevicesActivityBinding_Listener_startDiscovery_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> () {
    DevicesActivityBinding_ListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).startDiscovery( )
}

private typealias DevicesActivityBinding_Listener_validateBluetooth_1_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> ()

private func DevicesActivityBinding_Listener_validateBluetooth_1( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> () {
    DevicesActivityBinding_ListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).validateBluetooth( )
}

fileprivate class DevicesActivityBinding_ListenerLocal_: JNILocalProxy<DevicesActivityBinding_Listener, Any> {

    fileprivate static let _proxyClass: jclass = {
        var natives = [JNINativeMethod]()

        let DevicesActivityBinding_Listener_startDiscovery_0_thunk: DevicesActivityBinding_Listener_startDiscovery_0_type = DevicesActivityBinding_Listener_startDiscovery_0
        natives.append( JNINativeMethod( name: strdup("__startDiscovery"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( DevicesActivityBinding_Listener_startDiscovery_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let DevicesActivityBinding_Listener_validateBluetooth_1_thunk: DevicesActivityBinding_Listener_validateBluetooth_1_type = DevicesActivityBinding_Listener_validateBluetooth_1
        natives.append( JNINativeMethod( name: strdup("__validateBluetooth"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( DevicesActivityBinding_Listener_validateBluetooth_1_thunk, to: UnsafeMutableRawPointer.self ) ) )

        natives.append( JNINativeMethod( name: strdup("__finalize"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( JNIReleasableProxy__finalize_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let clazz = JNI.FindClass( proxyClassName() )
        natives.withUnsafeBufferPointer {
            nativesPtr in
            if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr.baseAddress, jint(nativesPtr.count) ) != jint(JNI_OK) {
                JNI.report( "Unable to register java natives" )
            }
        }

        defer { JNI.DeleteLocalRef( clazz ) }
        return JNI.api.NewGlobalRef( JNI.env, clazz )!
    }()

    override open class func proxyClassName() -> String { return "org/swiftjava/com_johnholdsworth/DevicesActivityBinding_ListenerProxy" }
    override open class func proxyClass() -> jclass? { return _proxyClass }

}

extension DevicesActivityBinding_Listener {

    public func localJavaObject( _ locals: UnsafeMutablePointer<[jobject]> ) -> jobject? {
        return DevicesActivityBinding_ListenerLocal_( owned: self, proto: self ).localJavaObject( locals )
    }

}

open class DevicesActivityBinding_ListenerBase: DevicesActivityBinding_Listener {

    public init() {}

    /// public abstract void com.johnholdsworth.swiftbindings.DevicesActivityBinding$Listener.startDiscovery()

    open func startDiscovery() /**/ {
    }


    /// public abstract void com.johnholdsworth.swiftbindings.DevicesActivityBinding$Listener.validateBluetooth()

    open func validateBluetooth() /**/ {
    }


}
