
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.DevicesActivityBinding$Responder ///

public protocol DevicesActivityBinding_Responder: JavaProtocol {

    /// public abstract void com.johnholdsworth.swiftbindings.DevicesActivityBinding$Responder.activateBluetooth()

    func activateBluetooth()

    /// public abstract void com.johnholdsworth.swiftbindings.DevicesActivityBinding$Responder.verifyGpsPermission()

    func verifyGpsPermission()

}


open class DevicesActivityBinding_ResponderForward: JNIObjectForward, DevicesActivityBinding_Responder {

    private static var DevicesActivityBinding_ResponderJNIClass: jclass?

    /// public abstract void com.johnholdsworth.swiftbindings.DevicesActivityBinding$Responder.activateBluetooth()

    private static var activateBluetooth_MethodID_3: jmethodID?

    open func activateBluetooth() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "activateBluetooth", methodSig: "()V", methodCache: &DevicesActivityBinding_ResponderForward.activateBluetooth_MethodID_3, args: &__args, locals: &__locals )
    }


    /// public abstract void com.johnholdsworth.swiftbindings.DevicesActivityBinding$Responder.verifyGpsPermission()

    private static var verifyGpsPermission_MethodID_4: jmethodID?

    open func verifyGpsPermission() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "verifyGpsPermission", methodSig: "()V", methodCache: &DevicesActivityBinding_ResponderForward.verifyGpsPermission_MethodID_4, args: &__args, locals: &__locals )
    }


}

