
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.DevicesActivityBinding ///

public protocol DevicesActivityBinding: JavaProtocol {

}


open class DevicesActivityBindingForward: JNIObjectForward, DevicesActivityBinding {

    private static var DevicesActivityBindingJNIClass: jclass?

}

