
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.jmarkstar.swiftbindings.MainActivitytBindings$Listener ///

public protocol MainActivitytBindings_Listener: JavaProtocol {

    /// public abstract void com.jmarkstar.swiftbindings.MainActivitytBindings$Listener.hello()

    func hello()

}


open class MainActivitytBindings_ListenerForward: JNIObjectForward, MainActivitytBindings_Listener {

    private static var MainActivitytBindings_ListenerJNIClass: jclass?

    /// public abstract void com.jmarkstar.swiftbindings.MainActivitytBindings$Listener.hello()

    private static var hello_MethodID_2: jmethodID?

    open func hello() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "hello", methodSig: "()V", methodCache: &MainActivitytBindings_ListenerForward.hello_MethodID_2, args: &__args, locals: &__locals )
    }


}

private typealias MainActivitytBindings_Listener_hello_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> ()

private func MainActivitytBindings_Listener_hello_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> () {
    MainActivitytBindings_ListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).hello( )
}

fileprivate class MainActivitytBindings_ListenerLocal_: JNILocalProxy<MainActivitytBindings_Listener, Any> {

    fileprivate static let _proxyClass: jclass = {
        var natives = [JNINativeMethod]()

        let MainActivitytBindings_Listener_hello_0_thunk: MainActivitytBindings_Listener_hello_0_type = MainActivitytBindings_Listener_hello_0
        natives.append( JNINativeMethod( name: strdup("__hello"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( MainActivitytBindings_Listener_hello_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

        natives.append( JNINativeMethod( name: strdup("__finalize"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( JNIReleasableProxy__finalize_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let clazz = JNI.FindClass( proxyClassName() )
        natives.withUnsafeBufferPointer {
            nativesPtr in
            if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr.baseAddress, jint(nativesPtr.count) ) != jint(JNI_OK) {
                JNI.report( "Unable to register java natives" )
            }
        }

        defer { JNI.DeleteLocalRef( clazz ) }
        return JNI.api.NewGlobalRef( JNI.env, clazz )!
    }()

    override open class func proxyClassName() -> String { return "org/swiftjava/com_jmarkstar/MainActivitytBindings_ListenerProxy" }
    override open class func proxyClass() -> jclass? { return _proxyClass }

}

extension MainActivitytBindings_Listener {

    public func localJavaObject( _ locals: UnsafeMutablePointer<[jobject]> ) -> jobject? {
        return MainActivitytBindings_ListenerLocal_( owned: self, proto: self ).localJavaObject( locals )
    }

}

open class MainActivitytBindings_ListenerBase: MainActivitytBindings_Listener {

    public init() {}

    /// public abstract void com.jmarkstar.swiftbindings.MainActivitytBindings$Listener.hello()

    open func hello() /**/ {
    }


}
