
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.jmarkstar.swiftbindings.MainActivitytBindings ///

public protocol MainActivitytBindings: JavaProtocol {

}


open class MainActivitytBindingsForward: JNIObjectForward, MainActivitytBindings {

    private static var MainActivitytBindingsJNIClass: jclass?

}

