
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.jmarkstar.swiftbindings.MainActivitytBindings$Responder ///

public protocol MainActivitytBindings_Responder: JavaProtocol {

}


open class MainActivitytBindings_ResponderForward: JNIObjectForward, MainActivitytBindings_Responder {

    private static var MainActivitytBindings_ResponderJNIClass: jclass?

}

