
/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.example.swiftbindings.MainActivitytBindings$Listener ///

package org.swiftjava.com_example;

@SuppressWarnings("JniMissingFunction")
public class MainActivitytBindings_ListenerProxy implements com.example.swiftbindings.MainActivitytBindings.Listener {

    // address of proxy object
    long __swiftObject;

    MainActivitytBindings_ListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    /// public abstract void com.example.swiftbindings.MainActivitytBindings$Listener.hello()

    public native void __hello( long __swiftObject );

    public void hello() {
        __hello( __swiftObject  );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
